root: true
env:
  es2021: true
  node: true
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended']
plugins: ['@typescript-eslint']
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
