name: Continuous integration
on: 
  pull_request:
jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: "Init repo"
        uses: actions/checkout@v3
      - name: "Init node"
        uses: actions/setup-node@v3
        with:
          node-versions: '18'
      - name: "Install dependencies"
        run: npm install
      - name: "Testing"
        run: npm run test
      - name: "Check lint"
        run: npm run lint